<a href="https://colab.research.google.com/github/Thanveerahmedshaik/Numpy/blob/main/basic_math_on_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
foo = np.array([[4,3],[1,0]])
bar = np.array([[1,2],[3,4]])
print(bar)
print(foo)

[[1 2]
 [3 4]]
[[4 3]
 [1 0]]


In [4]:
foo + bar  #values  added element wise

array([[5, 5],
       [4, 4]])

In [5]:
foo - bar

array([[ 3,  1],
       [-2, -4]])

In [6]:
foo * bar

array([[4, 6],
       [3, 0]])

In [7]:
foo/bar

array([[4.        , 1.5       ],
       [0.33333333, 0.        ]])

In [8]:
#Matrix multiplication

foo @ bar

array([[13, 20],
       [ 1,  2]])

In [9]:
foo

array([[4, 3],
       [1, 0]])

In [10]:
foo + np.full(shape = (2,2), fill_value=5)

array([[9, 8],
       [6, 5]])

In [11]:
foo + 5

array([[9, 8],
       [6, 5]])

In [16]:
np.full(shape = (3,3),fill_value=5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])