<a href="https://colab.research.google.com/github/Thanveerahmedshaik/Numpy/blob/main/challenge2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**After binge watching the discovery channel , you ditch your job as a trial lawyer to become a gold miner . You decide to prospect five locations underneath the 7*7 grid of land . How much gold do you uncover at each location?**

In [1]:
import numpy as np

In [8]:
np.random.seed(5555)
gold = np.random.randint(low= 1,high =10,size =(7,7))
print(gold)

[[3 4 1 6 3 1 4]
 [9 9 1 8 2 6 4]
 [1 2 7 3 2 5 6]
 [5 1 9 9 8 5 3]
 [8 1 8 3 2 9 3]
 [6 1 9 2 9 3 7]
 [5 4 3 1 8 9 1]]


In [9]:
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

In [10]:
print(locs)

[[0 4]
 [2 2]
 [2 3]
 [5 1]
 [6 3]]


In [11]:
gold_uncovered =[]
for loc in locs:
    gold_uncovered.append(gold[loc[0],loc[1]])
print(gold_uncovered)

[np.int64(3), np.int64(7), np.int64(3), np.int64(1), np.int64(1)]


In [12]:
gold

array([[3, 4, 1, 6, 3, 1, 4],
       [9, 9, 1, 8, 2, 6, 4],
       [1, 2, 7, 3, 2, 5, 6],
       [5, 1, 9, 9, 8, 5, 3],
       [8, 1, 8, 3, 2, 9, 3],
       [6, 1, 9, 2, 9, 3, 7],
       [5, 4, 3, 1, 8, 9, 1]])

In [13]:
gold[locs[:,0],locs[:,1]]
print(gold[locs[:,0],locs[:1]])

array([3, 7, 3, 1, 1])