In [1]:
import numpy as np

In [3]:
bar = np.array([[5,10,15,20],
               [25,30,35,40],
               [45,50,55,60]])

In [4]:
bar

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [5]:
print(bar)

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


In [40]:
 bar[1,2]

np.int64(1)

In [41]:
bar[0]

array([ 0, 10, 15,  1])

In [8]:
bar[0,None]

array([[ 5, 10, 15, 20]])

In [9]:
bar[:1]

array([[ 5, 10, 15, 20]])

In [10]:
bar[1:3,[-2,-1]]

array([[35, 40],
       [55, 60]])

In [12]:
bar[1:3,[-1,-2]]

array([[40, 35, 25],
       [60, 55, 45]])

In [13]:
bar[0,0] = -1

In [14]:
print(bar)

[[-1 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


In [15]:
#replacing rows

bar[1]=bar[2]
print(bar)

[[-1 10 15 20]
 [45 50 55 60]
 [45 50 55 60]]


In [16]:
bar[[0,1,2],[0,1,2]]  = [0,0,0] #[[0,1,2],[0,1,2]] first row first element second row second element and so on

print(bar)

[[ 0 10 15 20]
 [45  0 55 60]
 [45 50  0 60]]


In [30]:
print(bar[[2],[1]])

[50]


In [31]:
bar

array([[ 0, 10, 15, 20],
       [45,  0, 55, 60],
       [45, 50,  0, 60]])

In [32]:
bar[[0,1,2],[-1,-2,-3]] = [1,1,1]

In [33]:
bar

array([[ 0, 10, 15,  1],
       [45,  0,  1, 60],
       [45,  1,  0, 60]])

In [34]:
zoo = np.array([
    [
        [10,20],
        [20,30],
        [30,40]
    ],
    [
        [11,12],
        [13,14],
        [15,16]
    ]
]

)

In [35]:
print(zoo)

[[[10 20]
  [20 30]
  [30 40]]

 [[11 12]
  [13 14]
  [15 16]]]


In [37]:
zoo.ndim

3

In [39]:
#set first matrix of every row to of second column to 5

zoo[0,:,1] = 5
print(zoo)

[[[10  5]
  [20  5]
  [30  5]]

 [[11 12]
  [13 14]
  [15 16]]]
