<a href="https://colab.research.google.com/github/Thanveerahmedshaik/Numpy/blob/main/reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
foo = np.arange(start =1 ,stop = 9)
print(foo)

[1 2 3 4 5 6 7 8]


In [5]:
foo.reshape()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
np.reshape(foo, newshape=(4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
np.reshape(foo, newshape=(8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [9]:
bar = foo.reshape(2,4)
print(bar)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
bar.reshape(4,2)
print(bar)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
bar.reshape(4,2, order='F')

array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8]])

In [14]:
bar.reshape(4,2, order='C')

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
bar.reshape(4,2, order='A')

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
bar.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
bar.reshape(2,2,2,order='F')

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

In [18]:
bar.reshape(4,-1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
bar = bar.reshape(4,-1)
print(bar)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
bar.shape = (2,4)
print(bar)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
bar.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [22]:
np.transpose(bar)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])